#ifndef __MFS_PARAMS_H__
#define __MFS_PARAMS_H__

//For a 4GB SD Card
#define M_BLOCK_SIZE 512

//A 32 MB FS
#define M_NUM_BLOCKS 65536
#define M_BLOCKS_PER_CLUSTER 8
#define M_NUM_CLUSTERS M_NUM_BLOCKS/M_BLOCKS_PER_CLUSTER

#define M_LUT_ENTRY_SIZE 4*32
#define M_LUT_SIZE_BYTES M_NUM_CLUSTERS*M_LUT_ENTRY_SIZE
#define M_LUT_SIZE_BLOCKS M_NUM_CLUSTERS*M_LUT_ENTRY_SIZE/M_BLOCK_SIZE
#define M_LUT_SIZE_CLUSTERS M_NUM_CLUSTERS*M_LUT_ENTRY_SIZE/(M_BLOCK_SIZE*M_BLOCKS_PER_CLUSTER) /*Should be 24576*/

#define M_P 7937
#define M_N (M_NUM_CLUSTERS - M_LUT_SIZE_CLUSTERS)

#define M_NUM_RESIDENT_CLUSTERS 2

#endif